### PR TITLE
Add kotlin support

### PR DESCRIPTION
**Pull request by urielsalis**
Adds support for Kotlin 1.9 using a similar starter to the Java one.

### CODE REVIEW

**Comment by urielsalis** [comment]
Feel free to edit if needed!

**Comment by rohitpaulk** [comment]
Thanks for the PR @urielsalis - will take a look at this tomorrow 🙂 

Note to self: make sure we have a logo for Kotlin in the frontend app

**Comment by urielsalis** [comment]
Im not sure why the kotlin test is failing, seems like its not applying the diff correctly

I solved this challenge using Kotlin (based on this PR) in https://github.com/urielsalis/codecrafters-bittorrent-kotlin! :D

**Comment by rohitpaulk** [comment]
@urielsalis thanks for the link! I think that should be sufficient for us to figure out what the cause of the error is here. 

I wasn't able to get to this today, will try my best to tackle tomorrow!

**Comment by rohitpaulk** [comment]
The template compilation warning here is a bug, @libmartinito is looking into it in a separate PR. Will merge this now to test using the alpha status

**Pull request merged**
