### PR TITLE
add mvn command to java .your_bittorrent.sh

### PR DESCRIPTION
**Pull request by sarp**
Running `your_bittorrent.sh` in Java repo for the first time would give this error:

```
→ ./your_bittorrent.sh decode 5:hello
Error: Unable to access jarfile /tmp/codecrafters-bittorrent-target/java_bittorrent.jar
```

Adding `mvn package` command to shell script

### CODE REVIEW

**Comment by rohitpaulk** [comment]
@libmartinito could you test this locally, make sure it works fine and then deploy please?

**Comment by sarp** [comment]
weird, dunno why the test times out
does the tester use the script? the script doesn't have cached dependencies

**Comment by rohitpaulk** [comment]
@sarp the tester does use the script. There's a way around this using the precompile stuff though - @libmartinito will look into this 👍

**Comment by sarp** [comment]
fyi, I've noticed on other PRs that java test seems to get stuck without this change as well

**Comment by sarp** [comment]
will this pick up changes to code? 
say you edit `Main.java` and run `your_bittorrent.sh` again, it seems like this will only build the first time and never again

**Comment by libmartinito** [comment]
hm. maybe this is because i haven't done much java or gone through the bittorrent challenge. it seems that other challenges/languages could be done without using external dependencies. from what i read about maven, it seems like it's npm for java. i guess i just assumed that the user wouldn't reach for external dependencies. do you think it's better to comment it out instead and leave a note to uncomment if a user wants to run it locally?

**Comment by rohitpaulk** [comment]
@libmartinito let's try this locally: 

> Run `./your_bittorrent.sh`
> Edit Main.java, maybe change the print statement
> Try running `./your_bittorrent.sh` again

Does the new print statement reflect?

**Comment by rohitpaulk** [comment]
> it seems that mvn tries to check for/download dependencies even if we copied over files to app-cached.

@libmartinito Does this mean that there's no way to force `mvn` to hit a cached code path? i.e. even locally, if you run it twice with only changes to code (`Main.java`), it's slow the second time around?

**Comment by sarp** [comment]
mvn command isn't just to add dependencies, it's like the build command (creates the executable `java_bittorrent.jar`)
this is broken right now, `Main.java` will only compile the first time and never again

**Pull request merged**
