### PR TITLE
Add Support for Java

### PR DESCRIPTION
**Pull request by anugrahsinghal**
Hey @rohitpaulk, I was able to get the Java starter to work.

But there are some issues to be worked out, primarily because the Java template in `redis challenge` does not make use of external Jars or a build system, and for this challenge, we need external jars for JSON/Bencode.
So we need to get around that somehow.
Need your opinions on what to go forward with.

There are 3 options I explored:

## Using a build system - Maven
Pros:
Familiar build tool for Java Folks,
Easy to configure
Cons:
Slow inside docker run so fails the 10-sec timeout sometimes

## Using JBang
Pros:
Even more easier to configure than Maven
Can add support for languages like Kotlin/Groovy or upgrade JVM just by simple directives
Cons:
Slow inside docker run so fails the 10-sec timeout
A new tool that might be not as familiar to the user

## Copying Jars to the Classpath and run using plain Java
Pros:
Faster than the Maven/JBang process
Cons:
Needs Manual changes to add Jars to the classpath, so any jar user wants they will have to do it themselves.
Atypical setup so users might struggle with diff IDE setups not recognizing the external jar files.
Issues with starter_template because the `course-sdk/lib/stater_repository_defenition.rb::50` ruby script tries to `render` the file before copying and thus fails. I checked by manually placing the jars in the desired location and it worked fine.

```bash
workspace/course-sdk (main) $ docker compose run tester scripts/compile_and_test.sh courses/build-your-own-bittorrent java
```

<details>
<summary>Log</summary>



```ruby

/var/lib/gems/3.0.0/gems/mustache-1.1.1/lib/mustache/parser.rb:286:in `error': Illegal content in tag (Mustache::Parser::SyntaxError)
  Line 54
    ���'<\x1D�\x18����`�m��\\^�����=_��ZMs�[o<G�u��-�f^J����\x15黎�\x16�︓'�&\x15��\x02K�"pfu���f�ˆY�][6�8�ؖ������W����&�Zp�JjՖ��ת       w�ךAr�ś�ܵ�><��׶ǰү̨^��G2�-.yC�\x19^e{��GE��}�F\f�m\b�s��پ���i\x05/\aj#\x04�q�\x19�+u�>d0D�S/\x19��>ɗx;�}��\x16��/Qu�\\K,��<�;�Y%j`\x18�\r\f!i ���\a\f�}*ՠ__R  d\f�!ɐ>*s��KQ\f}mk�\x1F����\x17�ހR��_.>ݮ\x14���b�PdH.�\vώ\x0E0A�� =,\x11dT�h�Q��Y\aS��x�v[�\x11�9��\x06��>@$7s��� t$\b�h,�XF\x1Ck�Z�9:��   �y\\\0��E��`5JB\x11򾄱Pf����\x01m�\vb�6��Pc �U\x02����� �8����{1�=\x18\fW1\x1E2L��-�������]���0F�N�\b�\x1E\x0F��\x19|\x1D7��"y+[Z)S\a�C�>@�~��h\x17�E\x17'\x1Dr&\x03f$���o���OCn�\e\x19�����H\x04�\x1D�>OS�՟�\x06ca�\x0FPK\a\b1�{{�\x02\0\0�\x06\0\0PK\x03\x04\x14\0\b\b\b\0\0\0A\0\0\0\0\0\0\0\0\0\0\0\0\0I\0\0\0com/fasterxml/jackson/databind/AnnotationIntrospector$XmlExtensions.classŒ�J\x031\x14�oj���?�;�.ԅ��"ԪP�vQ\x17n�ifH��\x19&w�(�`.|\0\x1FJ�\x15�H\x11D\x11\x1A\bɗ䞜\x1C����\x02\0���AÃM\x01����J��%��\x02�w���e�\x1C�t\x1AGr��[gQ�\x15�\x11��~\x10�K�$:�Z\fL���� ��%�'�A��H��{���S2R\x18�!�\x06ö��Є�(K��㯍\x1C�����q����:�C�8ʈ]=,!�Sk#��==-'��@=\x0F�ZOI@#_螱����f��/L�qm\c?
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         ^
        from /var/lib/gems/3.0.0/gems/mustache-1.1.1/lib/mustache/parser.rb:196:in `scan_tags'
        from /var/lib/gems/3.0.0/gems/mustache-1.1.1/lib/mustache/parser.rb:134:in `compile'
        from /var/lib/gems/3.0.0/gems/mustache-1.1.1/lib/mustache/template.rb:59:in `tokens'
        from /var/lib/gems/3.0.0/gems/mustache-1.1.1/lib/mustache/template.rb:50:in `compile'
        from /var/lib/gems/3.0.0/gems/mustache-1.1.1/lib/mustache/template.rb:36:in `render'
        from /var/lib/gems/3.0.0/gems/mustache-1.1.1/lib/mustache.rb:137:in `render'
        from /var/lib/gems/3.0.0/gems/mustache-1.1.1/lib/mustache.rb:97:in `render'
        from /course-sdk/lib/starter_template_compiler/starter_repository_definition.rb:50:in `block in files'
        from /course-sdk/lib/starter_template_compiler/starter_repository_definition.rb:45:in `map'
        from /course-sdk/lib/starter_template_compiler/starter_repository_definition.rb:45:in `files'
        from /course-sdk/lib/starter_template_compiler/compiler.rb:40:in `compile_definition'
        from /course-sdk/lib/starter_template_compiler/compiler.rb:30:in `block in compile_for_language'
        from /course-sdk/lib/starter_template_compiler/compiler.rb:26:in `each'
        from /course-sdk/lib/starter_template_compiler/compiler.rb:26:in `compile_for_language'
        from scripts/compile.rb:29:in `block in <main>'
        from scripts/compile.rb:29:in `each'
        from scripts/compile.rb:29:in `<main>'
        
```
</details>


### Possible Solutions:
- Use Maven:
  - To Address Slowness: Increase Timeout OR Pre-compile the Jar before test timer starts, so all runs do not need to compile+create archive.
- Use JBang:
  - To Address Slowness: Increase Timeout OR Pre-compile the Jar before test timer starts, so all runs do not need to compile+create archive.
- Copy Jars:
  - To Address Manual copy: create a helper script that downloads and adds jar to the desired location.
  - To Address IDE setup issues: there might be conventions that ide's follow as to where to look for external jars, IIRC it is the `libs/` directory at the same level.
  - To Address the render: Change the logic for the ruby script. (Might need help in this)
  
I saw something in the `rust dockerfile` related to precompile, but could not figure out how to use it.
Could someone help me out with it?

My preference would be to use a Build System like Maven.

---

Open to your inputs :)
Please let me know if I can help clarify this more.

### CODE REVIEW

**Comment by rohitpaulk** [comment]
@anugrahsinghal yep, precompile seems like the right approach here. If Maven is standard, makes sense to try to get that to work here.

The way the precompile stuff works is: 

- Any script placed inside `/codecrafters-precompile.sh` will be executed before the tests start
  - [Example](https://github.com/codecrafters-io/build-your-own-grep/blob/95e8741de8ef2d6de86e606697c49f5e6d81f15b/dockerfiles/haskell-9.2.Dockerfile#L30)
- Any files placed inside `/app-cached` when the dockerfile builds will be moved into `/app` along with the user's code before tests start. 
  - This helps with languages which need to place some cached objects inside the app directory.
  - [Example](https://github.com/codecrafters-io/build-your-own-sqlite/blob/00ac8615a90bd3f180e5a1d15746fc98cb68c930/dockerfiles/python-3.8.Dockerfile#L20)
  
Both of these techniques are utilized inside the Dockerfile, the starter code itself won't be aware of this in general. 
  
Up until now, we've found this combination sufficient to make most languages work. Could you try and see if this helps?

**Comment by anugrahsinghal** [comment]
@rohitpaulk got the build working locally with both precompile and cache.

But, looks like the build specifically for Java gets stuck when running on github.
All my actions failed only for java: https://github.com/anugrahsinghal/build-your-own-bittorrent/actions

and the same seems here too.

---

I faced this on my local system too, and on gitpod.

If I press ctrl+c to stop execution, I get this log.

```shell
  - Building java-1.8 image without cache

^C/course-sdk/lib/test_harness.rb:117:in `copy_stream': Interrupt
        from /course-sdk/lib/test_harness.rb:117:in `setup_io_relay'
        from /course-sdk/lib/test_harness.rb:56:in `assert_stderr_contains'
        from /course-sdk/lib/dockerfile_tester.rb:47:in `build_image'
        from /course-sdk/lib/dockerfile_tester.rb:35:in `block in do_test'
        from /course-sdk/lib/test_harness.rb:135:in `assert_time_under'
        from /course-sdk/lib/dockerfile_tester.rb:35:in `do_test'
        from /course-sdk/lib/test_harness.rb:44:in `test'
        from scripts/test.rb:83:in `block in <main>'
        from scripts/test.rb:83:in `each'
        from scripts/test.rb:83:in `<main>'
```

I do not understand RUBY so,
I pasted the error and source code into `perplexity codellama-34-b` and got this fix.

```ruby

# It looks like the issue might be related to the MultiWriter class. Specifically, the PrefixedLineWriter instance is never closed, which could cause the program to hang.

def setup_io_relay(source, prefixed_destination, other_destination)
  begin
    IO.copy_stream(
      source,
      MultiWriter.new(
        PrefixedLineWriter.new("     ", prefixed_destination),
        other_destination
      )
    )
  rescue Exception => e
    puts "Error occurred while relaying IO streams: #{e}"
  ensure
    # Close the writers
    prefixed_writer = PrefixedLineWriter.new("     ", prefixed_destination)
    other_writer = other_destination
    prefixed_writer.close
    other_writer.close
  end
end
```

After applying the fix on gitpod,
I do not seem to face any errors (tried running it multiple times), but that might be _coincidental_.

I tried to modify the `test.yml` file to refer to it to test my fix
but does not look like I can use the fix directly from my fork of the repo
https://github.com/anugrahsinghal/codecrafters-course-sdk/tree/close_io_relay

any help/direction is appreciated.

**Comment by anugrahsinghal** [comment]
got the workflow to use my branch with the modified ruby script on my fork.

https://github.com/anugrahsinghal/build-your-own-bittorrent/actions/runs/6114448063/job/16596033579?pr=1

But looks like the build still fails for Java.

**Comment by anugrahsinghal** [comment]
the issue with the script getting stuck is fixed.
reducing the amount of log that is being produced during the docker build fixed the issue.

**Comment by anugrahsinghal** [comment]
post-diffs test is failing due to an HTTP 403 (Forbidden) issue.

https://github.com/codecrafters-io/build-your-own-bittorrent/actions/runs/6115454311/job/16599642025?pr=12#step:4:127

**Comment by rohitpaulk** [comment]
Thanks so much for working on this @anugrahsinghal! Gonna test this and should be live shortly

**Pull request merged**
